# Generated by Django 2.0.1 on 2020-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_goodsimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='商品名'),
        ),
    ]
